apiVersion: spacexui/v1
kind: Deployment
metadata:
  name: spacexui-depl
sepc:
  replicas: 1
  selector:
    matchLabels:
      app: ui-client
  template:
    metadata:
      labels:
        app: ui-client
    spec:
      containers:
        - name: spacexui
          image: spacex/ui
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: ui-client-srv
spec:
  selector:
    app: ui-client
  ports:
    - name: ui-client
      protocol: TCP
      port: 3000
      targetPort: 3000