apiVersion: spacexservice/v1
kind: Deployment
metadata:
  name: spacexservice-depl
sepc:
  replicas: 1
  selector:
    matchLabels:
      app: spacex-service
  template:
    metadata:
      labels:
        app: spacex-service
    spec:
      containers:
        - name: spacexservice
          image: spacex/xservice
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: spacex-service-srv
spec:
  selector:
    app: spacex-service
  ports:
    - name: spacex-service
      protocol: TCP
      port: 4000
      targetPort: 4000