name: spaceX

on:
  push:
    branches: [ master ]
    paths:
      - 'packages/space-x/**'

defaults:
  run:
    working-directory: packages/space-x

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
      # - uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_SPACE_X }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SPACE_X }}
      #     aws-region: us-east-2
      # - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME}}
